### ISSUE TITLE
Fedora 35 w/ original generation chromecast

### ISSUE THREAD

**Issue by ctpforr** [garak92/librechromecast#3]
Choosing a file to cast only gives me a black screen with the chromecast icon on it on my tv.

The only error I see is at launch:

`[161950:1231/144543.800988:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
`

Let me know where to find any logs you might be interested in or whether I need to upgrade my CC.

**Comment by garak92** [comment]
Hello. Thanks for reporting your problem. Please, I ask you to do the following:

- Check /etc/nsswitch.conf and see if there is a mdns4_minimal [NOTFOUND=return] on hosts (more info here:https://dashkiosk.readthedocs.io/en/latest/chromecast.html). I had to do this on Arch, maybe some distros do not have this by default.

- Please go into View -> Toogle Developer Tools -> Console. Try to cast something again, and paste the output of the Console here. 

- Try to cast another file, or a YouTube video, and let me know if it works. This may help narrow down the issue.

**Comment by ctpforr** [comment]
The nsswitch.conf is set up:
```
hosts:      files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
```

Console:
```
2requests.js:156 Local ip 192.168.86.121
uploader.js:16 My file is: http://192.168.86.121:5000/home/asdf/Videos/vid.mp4
requests.js:15 200
2requests.js:140 Device name Master Bedroom TV﻿```

Are there any dependencies?

Happy New Year!     I probably won't be able to gather too much more data.   Good luck!

**Comment by garak92** [comment]
There no specific dependencies. If your system has avahi and nsswitch (which most distros do), you should be able to get it running.

What is weird is that the response returns 200, so theoretically everything is OK. 

When you have the time, do this:
With the application opened, copy and paste http://192.168.86.121:5000/home/asdf/Videos/vid.mp4 into a browser and see if the video gets played there. If not, then the program is not reading your filename or path correctly for some reason. 

- Check if the app works with a YouTube url (there is an input field on the left side of the app for you to copy YouTube URLs). If this works, this means that the application is indeed able to communicate with your device and cast media. So it must be something else. 

A wonderful 2022 for you, and thanks again for your help!

**Comment by ctpforr** [comment]
YouTube links work fine.   

When I play my file, it does change the CC to the black screen w/CC logo, and then when I hit 'stop' the CC goes back to the default screen, so it seems to be communicating, just not completly.

FWIW I am now very toasted and it's just over an hour 'til midnight.   Why am I here?   I dunno!   Happy New Year (again) :-)

**Comment by garak92** [comment]
The behavior you are describing is exactly what happens when you try to cast something but you haven't selected any media. So, I am sure the program is missconstructing the path to your file for some reason.

The only way we would know what exactly is being missconstructed is if you compare the path shown in the console log you showed me previously with the actual path of your file.

PD: I couldn't get toasted because I had to drive :'(

**Comment by ctpforr** [comment]
I've solved it.   I had to open port 5000 on my firewall (duh!).   Realized it when I tried the url in a browser on my phone and then laptop.    Pretty obvious.   Perhaps add a note in the README.md?
